import type { CopingTool } from "./recommendationService.js";

export const DEFAULT_COPING_TOOLS: CopingTool[] = [
  {
    id: "box-breathing",
    title: "Box Breathing",
    description: "4-4-4-4 breathing to manage stress",
    category: "breathing",
    supportedMoods: ["anxious", "frustrated", "neutral"],
    intensityLevel: "high",
    durationMinutes: 2,
    type: "box-breathing",
  },
  {
    id: "478-breathing",
    title: "4-7-8 Breathing",
    description: "Deeply calming breath pattern for sleep and anxiety",
    category: "breathing",
    supportedMoods: ["anxious", "frustrated", "sad", "neutral"],
    intensityLevel: "medium",
    durationMinutes: 3,
    type: "478-breathing",
  },
  {
    id: "simple-breathing",
    title: "Simple Breathing",
    description: "Gentle 4-4 breathing to calm your nervous system",
    category: "breathing",
    supportedMoods: ["anxious", "frustrated", "neutral", "calm"],
    intensityLevel: "low",
    durationMinutes: 2,
    type: "breathing",
  },
  {
    id: "54321-grounding",
    title: "5-4-3-2-1 Grounding",
    description: "Use your senses to anchor in the present moment",
    category: "grounding",
    supportedMoods: ["anxious", "frustrated", "sad"],
    intensityLevel: "high",
    durationMinutes: 3,
    type: "grounding",
  },
  {
    id: "body-scan",
    title: "Body Scan Meditation",
    description: "Notice sensations from head to toe",
    category: "grounding",
    supportedMoods: ["anxious", "frustrated", "neutral", "calm"],
    intensityLevel: "medium",
    durationMinutes: 5,
    type: "body-scan",
  },
  {
    id: "progressive-muscle-relaxation",
    title: "Progressive Muscle Relaxation",
    description: "Tense and release muscle groups",
    category: "grounding",
    supportedMoods: ["anxious", "frustrated", "neutral"],
    intensityLevel: "medium",
    durationMinutes: 7,
    type: "pmr",
  },
  {
    id: "cognitive-reframing",
    title: "Cognitive Reframing",
    description: "Challenge unhelpful thoughts with questions",
    category: "cognitive",
    supportedMoods: ["anxious", "sad", "frustrated", "neutral"],
    intensityLevel: "medium",
    durationMinutes: 5,
    type: "cognitive-reframing",
  },
  {
    id: "thought-journaling",
    title: "Thought Journaling",
    description: "Write down thoughts to gain perspective",
    category: "cognitive",
    supportedMoods: ["anxious", "sad", "frustrated", "neutral"],
    intensityLevel: "low",
    durationMinutes: 10,
    type: "thought-journaling",
  },
  {
    id: "affirmations",
    title: "Self-Affirmations",
    description: "Gentle reminders of strength and resilience",
    category: "reflection",
    supportedMoods: ["sad", "frustrated", "neutral", "anxious"],
    intensityLevel: "low",
    durationMinutes: 2,
    type: "affirmations",
  },
  {
    id: "gratitude-reflection",
    title: "Gratitude Reflection",
    description: "Notice three things you are grateful for",
    category: "reflection",
    supportedMoods: ["sad", "neutral", "calm", "happy"],
    intensityLevel: "low",
    durationMinutes: 3,
    type: "gratitude",
  },
  {
    id: "self-compassion",
    title: "Self-Compassion Break",
    description: "Speak to yourself with kindness",
    category: "reflection",
    supportedMoods: ["sad", "frustrated", "anxious", "neutral"],
    intensityLevel: "low",
    durationMinutes: 4,
    type: "self-compassion",
  },
  {
    id: "quick-exercises",
    title: "Movement Reset",
    description: "Simple movements to release tension",
    category: "movement",
    supportedMoods: ["frustrated", "anxious", "neutral", "happy"],
    intensityLevel: "medium",
    durationMinutes: 5,
    type: "exercises",
  },
];
